package com.bettercontent.threads;

import com.google.gson.JsonParser;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraftforge.client.event.RenderGuiEvent;
import org.lwjgl.glfw.GLFW;
import org.junit.jupiter.api.Test;
import javax.imageio.ImageIO;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

final class ThreadContractsTest {
    @Test void clientLoadingAccessorDeclaresItsProductionRefmap() throws Exception {
        String mixins = Files.readString(Path.of("src/main/resources/better_content_threads.mixins.json"));
        assertTrue(mixins.contains("\"refmap\": \"better_content_threads.refmap.json\""));
    }
    @Test void catalogueContainsFourOrderedSuitsOfThirteen(){assertEquals(52,ThreadArt.IDS.size());assertEquals(52,new HashSet<>(ThreadArt.IDS).size());for(var suit:ThreadSuit.values())assertEquals(java.util.stream.IntStream.rangeClosed(1,13).boxed().toList(),ThreadArt.ENTRIES.stream().filter(e->e.suit()==suit).map(ThreadArt.Entry::order).toList());}
    @Test void exactAssignmentsCoverEveryIdentity(){assertEquals(new HashSet<>(ThreadArt.IDS),ThreadArt.EXPECTED_ASPECTS.keySet());var retained=Map.ofEntries(Map.entry("stone_makes_promises",ThreadAspect.WORK),Map.entry("world_remembers",ThreadAspect.CONTROL),Map.entry("deep_own_light",ThreadAspect.ROBUSTNESS),Map.entry("silence_has_teeth",ThreadAspect.ENDURANCE),Map.entry("feast_before_journey",ThreadAspect.ENDURANCE),Map.entry("materials_temperaments",ThreadAspect.ROBUSTNESS),Map.entry("pressure_changes_matter",ThreadAspect.IMPACT),Map.entry("rails_turn_distance",ThreadAspect.TEMPO),Map.entry("leave_atmosphere",ThreadAspect.ENDURANCE),Map.entry("blood_infrastructure",ThreadAspect.RENEWAL),Map.entry("army_walks_toward_you",ThreadAspect.IMPACT));retained.forEach((id,aspect)->assertEquals(aspect,ThreadArt.EXPECTED_ASPECTS.get(id),id));assertEquals(ThreadAspect.CONTROL,ThreadArt.EXPECTED_ASPECTS.get("sleep_is_not_an_anchor"));assertEquals(ThreadAspect.TEMPO,ThreadArt.EXPECTED_ASPECTS.get("the_body_learns_new_motions"));}
    @Test void definitionsRequireTeachingOwnershipAndRoutes(){var json=JsonParser.parseString("{\"id\":\"test\",\"concept_id\":\"test.rule\",\"owner\":\"test-producer\",\"title\":\"Test\",\"suit\":\"world\",\"order\":1,\"aspect\":\"control\",\"art\":\"better_content_threads:textures/gui/threads/test.png\",\"rule\":\"This deliberately plain teaching rule contains enough words to satisfy the concise learning contract for every active card in the catalogue.\",\"prose\":\"Prose\",\"invitation\":\"Invitation\",\"action\":\"Do it.\",\"reveal_routes\":[{\"id\":\"r\",\"label\":\"Reveal\",\"type\":\"event\",\"value\":\"a\",\"producer\":\"test-producer\",\"correlation\":\"episode\"}],\"completion_routes\":[{\"id\":\"c\",\"label\":\"Complete\",\"type\":\"event\",\"value\":\"b\",\"producer\":\"test-producer\",\"correlation\":\"episode\"}]}").getAsJsonObject();var definition=ThreadDefinition.parse(json);assertEquals("test.rule",definition.conceptId());assertNull(definition.doorway());json.remove("completion_routes");assertThrows(IllegalArgumentException.class,()->ThreadDefinition.parse(json));}
    @Test void catalogueHasNoFtbDoorwaysAndUsesExactNativeReplacements()throws Exception{var catalogue=JsonParser.parseString(Files.readString(Path.of("src/main/resources/data/better_content_threads/threads/catalogue.json"))).getAsJsonObject().getAsJsonArray("threads");var doorways=new HashMap<String,String>();for(var element:catalogue){var json=element.getAsJsonObject();if(!json.has("doorway")||json.get("doorway").isJsonNull())continue;var doorway=json.getAsJsonObject("doorway");assertNotEquals("ftb",doorway.get("type").getAsString());doorways.put(json.get("id").getAsString(),doorway.get("type").getAsString()+":"+doorway.get("target").getAsString());}assertEquals("font:minecraft:the_nether",doorways.get("fire_has_country"));assertEquals("font:aether:the_aether",doorways.get("sky_another_country"));assertEquals("font:the_bumblezone:the_bumblezone",doorways.get("deep_own_light"));assertEquals("font:rats:ratlantis",doorways.get("silence_has_teeth"));assertEquals("ponder:create:hand_crank",doorways.get("motion_becomes_industry"));assertEquals("ponder:create:large_water_wheel",doorways.get("rivers_turn_work"));assertEquals("emi:create:precision_mechanism",doorways.get("precision_has_rhythm"));assertEquals("emi:powergrid:generator_housing",doorways.get("electricity_agreement"));assertEquals("ponder:create:track_station",doorways.get("rails_turn_distance"));assertEquals("emi:vs_eureka:oak_ship_helm",doorways.get("vessel_becomes_place"));assertEquals("emi:creatingspace:rocket_controls",doorways.get("leave_atmosphere"));assertFalse(doorways.containsKey("ruins_are_instructions"));}
    @Test void everyRouteHasExactProducerAndCorrelationCoverage()throws Exception{var catalogue=JsonParser.parseString(Files.readString(Path.of("src/main/resources/data/better_content_threads/threads/catalogue.json"))).getAsJsonObject().getAsJsonArray("threads");int routes=0;var keys=new HashSet<String>();for(var element:catalogue){var definition=ThreadDefinition.parse(element.getAsJsonObject());for(var route:java.util.stream.Stream.concat(definition.revealRoutes().stream(),definition.completionRoutes().stream()).toList()){routes++;assertFalse(route.producer().isBlank());assertEquals("episode",route.correlation());assertTrue(keys.add(definition.id()+":"+route.id()));}}assertEquals(108,routes);assertEquals(108,keys.size());}
    @Test void aspectsAndSuitsUseCanonicalIdsAndColors(){assertEquals(0xFF4055,ThreadAspect.IMPACT.color());assertEquals(0x00A985,ThreadAspect.TEMPO.color());assertEquals(0xF0E2C5,ThreadAspect.WORK.color());assertEquals(0xE0B01F,ThreadAspect.MOBILITY.color());assertEquals(0x52606A,ThreadAspect.ENDURANCE.color());assertEquals(0xAF6A2F,ThreadAspect.ROBUSTNESS.color());assertEquals(0x6CCAF0,ThreadAspect.RENEWAL.color());assertEquals(0x8E5BB7,ThreadAspect.CONTROL.color());assertEquals(0x66704C,ThreadSuit.WORLD.color());assertEquals(0x805356,ThreadSuit.FRAGILITY.color());assertThrows(IllegalArgumentException.class,()->ThreadAspect.parse("Control"));assertThrows(IllegalArgumentException.class,()->ThreadSuit.parse("World"));}
    @Test void noticePayloadContainsNoGameAssetOrProse(){var notice=new ThreadNetwork.Notice(ThreadNetwork.NoticeKind.REVEAL,"world_remembers","The World Remembers","world","endurance");assertAll(()->assertEquals(ThreadNetwork.NoticeKind.REVEAL,notice.kind()),()->assertEquals("world_remembers",notice.id()),()->assertEquals("The World Remembers",notice.title()),()->assertEquals("world",notice.suit()),()->assertEquals("endurance",notice.aspect()));assertThrows(IllegalArgumentException.class,()->new ThreadNetwork.Notice(ThreadNetwork.NoticeKind.REVEAL,"world_remembers","The World Remembers","world","Control"));}
    @Test void automaticTeaseUsesSmallCodeGlyphLockup(){assertEquals(8,ThreadClient.NOTICE_GLYPH_SIZE);assertTrue(ThreadClient.NOTICE_TEXT_SCALE<1);assertEquals(2,ThreadClient.NOTICE_TEXT_OFFSET_Y-(ThreadClient.NOTICE_GLYPH_OFFSET_Y+ThreadClient.NOTICE_GLYPH_SIZE));assertTrue(ThreadClient.NOTICE_HINT_SCALE<ThreadClient.NOTICE_TEXT_SCALE);assertTrue(ThreadClient.NOTICE_HINT_OFFSET_Y>ThreadClient.NOTICE_TEXT_OFFSET_Y);}
    @Test void automaticTeaseUsesExactLocalizedCopy()throws Exception{var lang=JsonParser.parseString(Files.readString(Path.of("src/main/resources/assets/better_content_threads/lang/en_us.json"))).getAsJsonObject();assertEquals("You've revealed the card: %s",lang.get("message.better_content_threads.thread_revealed").getAsString());assertEquals("%s · Open Threads",lang.get("message.better_content_threads.thread_reader_hint").getAsString());}
    @Test void readerUsesNativeConflictAwareMMapping()throws Exception{assertEquals("key.better_content_threads.open_reader",ThreadClient.OPEN.getName());assertEquals(GLFW.GLFW_KEY_M,ThreadClient.OPEN.getDefaultKey().getValue());String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadClient.java"));assertTrue(source.contains("if (OPEN.consumeClick()) ThreadNetwork.request(\"open\", \"\")"));assertFalse(source.contains("GLFW_KEY_J"));assertFalse(source.contains("GLFW_MOD_CONTROL"));}
    @Test void automaticTeaseRendersOnceAfterTheWholeGui(){java.util.function.Consumer<RenderGuiEvent.Post> handler=ThreadClient::render;assertNotNull(handler);}
    @Test void cardArtScalesTheEntireNativeTexture()throws Exception{assertEquals(256,ThreadClient.ART_TEXTURE_WIDTH);assertEquals(384,ThreadClient.ART_TEXTURE_HEIGHT);String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadClient.java"));assertTrue(source.contains("graphics.blit(id, x, y, width, height, 0.0f, 0.0f,"));}
    @Test void detailLayoutCentersTheSplitCompositionAtWideAndCompactSizes(){for(var size:List.of(new int[]{854,480},new int[]{320,240})){var layout=ThreadDeckScreen.detailLayout(size[0],size[1]);int contentWidth=layout.cardWidth()+18+layout.panelWidth();assertTrue(Math.abs((layout.cardX()*2+contentWidth)-size[0])<=1);assertEquals(layout.cardX()+layout.cardWidth()+18,layout.detailsX());assertTrue(layout.cardHeight()<=300);assertTrue(Math.abs(layout.cardWidth()*3-layout.cardHeight()*2)<=2);}}
    @Test void readerLocalizesExplicitRevealCues()throws Exception{var lang=JsonParser.parseString(Files.readString(Path.of("src/main/resources/assets/better_content_threads/lang/en_us.json"))).getAsJsonObject();assertEquals("REVEAL",lang.get("screen.better_content_threads.reveal_badge").getAsString());assertEquals("%1$s of 13 remembered · %2$s to reveal",lang.get("screen.better_content_threads.catalogue_status_unread").getAsString());String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadDeckScreen.java"));assertTrue(source.contains("unreadCount(candidate)"));assertTrue(source.contains("selected = firstUnreadIndex(suitCards())"));assertTrue(source.contains("scrollRow = selected / CATALOGUE_COLUMNS"));}
    @Test void noticesQueueByKindAndPauseWithoutAdvancing(){var queue=new ThreadNoticeQueue<String>(value->value);queue.addAll(List.of("reveal:first","complete:first","reveal:first"));assertEquals(2,queue.size());var first=queue.advance(0,false);assertEquals("reveal:first",first.notice());assertTrue(first.started());assertEquals(0,queue.advance(900,true).elapsedMs());assertNull(queue.advance(3_200,false));assertEquals("complete:first",queue.advance(0,false).notice());}
    @Test void readStateChangesOnlyAfterEightHundredMillisecondDevelopment(){var reveal=new ThreadRevealState();reveal.select(true);assertEquals(ThreadRevealState.Activation.STARTED,reveal.activate());assertFalse(reveal.advance(799));assertTrue(reveal.advance(1));assertEquals(ThreadRevealState.Phase.COMPLETE,reveal.phase());}
    @Test void developmentSkipIsConsumedBeforeControls(){var reveal=new ThreadRevealState();reveal.select(true);assertEquals(ThreadRevealState.Activation.STARTED,reveal.activate());assertEquals(ThreadRevealState.Activation.COMPLETED,reveal.activate());assertEquals(ThreadRevealState.Activation.IGNORED,reveal.activate());}
    @Test void runtimeArtUsesOnlyUntouchedImagesAndThumbnails()throws Exception{Path root=Path.of("src/main/resources/assets/better_content_threads/textures/gui/threads");try(var files=Files.list(root)){var names=files.filter(Files::isRegularFile).map(path->path.getFileName().toString()).toList();assertEquals(104,names.size());assertFalse(names.stream().anyMatch(name->name.endsWith("_archive.png")||name.endsWith("_pigment.png")||name.endsWith("_aspect.png")));}for(String id:ThreadArt.IDS){for(String suffix:List.of(".png","_thumb.png")){var image=ImageIO.read(root.resolve(id+suffix).toFile());assertNotNull(image,id+suffix);assertEquals(256,image.getWidth(),id+suffix);assertEquals(384,image.getHeight(),id+suffix);}}}
    @Test void retainedArtContainsNoLegacyExactTracePixels()throws Exception{var legacy=Map.of(ThreadAspect.IMPACT,0xE4717D,ThreadAspect.TEMPO,0xAA652B,ThreadAspect.WORK,0xCAA903,ThreadAspect.MOBILITY,0xC0E304,ThreadAspect.ENDURANCE,0x35BBD0,ThreadAspect.ROBUSTNESS,0x1175FC,ThreadAspect.RENEWAL,0x6FEDBA,ThreadAspect.CONTROL,0x8A6CB2);var replacements=Set.of("sleep_is_not_an_anchor","hunger_is_not_nutrition","food_carries_weather","coins_do_not_climb","the_end_is_not_a_door","recipes_obey_this_world","the_body_learns_new_motions");Path root=Path.of("src/main/resources/assets/better_content_threads/textures/gui/threads");for(var entry:ThreadArt.ENTRIES){if(replacements.contains(entry.id()))continue;for(String suffix:List.of(".png","_thumb.png")){var image=ImageIO.read(root.resolve(entry.id()+suffix).toFile());for(int y=0;y<image.getHeight();y++)for(int x=0;x<image.getWidth();x++)assertNotEquals(legacy.get(entry.aspect()).intValue(),image.getRGB(x,y)&0xFFFFFF,entry.id()+suffix);}}}
    @Test void oldStateIsIntentionallyIgnoredAtTheCleanBreak(){var root=new CompoundTag();var collected=new ListTag();collected.add(StringTag.valueOf("world_remembers"));root.put("collected",collected);var state=ThreadPlayerState.fromTag(root);assertTrue(state.known.isEmpty());assertTrue(state.completed.isEmpty());assertEquals(0,state.completionCounts.size());}
    @Test void emptyLineageImportsWorldLocalStateButEstablishedLineageWins(){var local=new CompoundTag();local.putString("source","world");var lineage=new CompoundTag();assertSame(local,ThreadPlayerState.preferLineageState(lineage,local));lineage.putString("source","lineage");assertSame(lineage,ThreadPlayerState.preferLineageState(lineage,local));}
    @Test void completionHistoryIsMonotonicAndRouteAware(){var root=new CompoundTag();root.putInt("schema",4);var known=new ListTag();known.add(StringTag.valueOf("world_remembers"));root.put("known",known);var active=new ListTag();active.add(StringTag.valueOf("world_remembers"));root.put("active",active);var state=ThreadPlayerState.fromTag(root);assertTrue(state.complete("world_remembers","Returned trace",3));assertFalse(state.complete("world_remembers","Returned trace",3));assertEquals(1,state.completionCounts.get("world_remembers"));assertEquals("Returned trace ×1",state.routeSummary("world_remembers"));}
    @Test void correlationsPersistRebindAndClearOnlyAfterCompletion(){var state=new ThreadPlayerState();assertTrue(state.reveal("world_remembers","episode-a"));assertEquals("episode-a",state.correlations.get("world_remembers"));var restored=ThreadPlayerState.fromTag(state.toTag());assertEquals("episode-a",restored.correlations.get("world_remembers"));assertTrue(restored.bindCorrelation("world_remembers","episode-b"));assertEquals("episode-b",restored.correlations.get("world_remembers"));assertTrue(restored.complete("world_remembers","Returned trace",1));assertFalse(restored.correlations.containsKey("world_remembers"));}
    @Test void knownCardReactivatesInSuccessorWithoutBecomingUnreadAgain(){var state=new ThreadPlayerState();assertTrue(state.reveal("world_remembers"));assertTrue(state.markRead("world_remembers"));state.enterGeneration(1);assertTrue(state.reveal("world_remembers"));assertTrue(state.active.contains("world_remembers"));assertFalse(state.unread.contains("world_remembers"));assertFalse(state.reveal("world_remembers"));}
    @Test void loadingBriefRotationResumesAtNextUnseenAndCyclesInOrder(){var briefs=List.of(LoadingBriefs.FALLBACK,new LoadingBrief("second","learning.second","test-owner","","Practice","Second lesson","This deliberately concise loading lesson contains enough plain words to satisfy the required communication contract while explaining a useful changed rule without revealing progression spoilers.","Practice this rule before danger arrives.",new net.minecraft.resources.ResourceLocation("minecraft","textures/item/book.png")));var state=new LoadingBriefRotation.State(Set.of(),"");assertEquals("threads",LoadingBriefRotation.select(briefs,state).id());state=LoadingBriefRotation.commit(state,List.of("threads"),briefs);assertEquals("second",LoadingBriefRotation.select(briefs,state).id());state=LoadingBriefRotation.commit(state,List.of("second"),briefs);assertEquals("threads",LoadingBriefRotation.select(briefs,state).id());}
    @Test void loadingBriefSessionWrapsManuallyAndRequiresExplicitCarryOver(){var briefs=List.of(LoadingBriefs.FALLBACK,new LoadingBrief("second","learning.second","test-owner","","Practice","Second lesson","This deliberately concise loading lesson contains enough plain words to satisfy the required communication contract while explaining a useful changed rule without revealing progression spoilers.","Practice this rule before danger arrives.",new net.minecraft.resources.ResourceLocation("minecraft","textures/item/book.png")));var session=new LoadingBriefSession(briefs,new LoadingBriefRotation.State(Set.of(),""));assertFalse(session.keepReading());assertTrue(session.toggleKeepReading());assertEquals("second",session.move(-1).id());assertEquals("threads",session.move(1).id());assertEquals(List.of("threads","second"),session.viewed());}
    @Test void loadingBriefHistoryAcceptsLegacySchemaLessState(){var legacy=JsonParser.parseString("{\"seen\":[\"threads\",\"water\"],\"last\":\"water\"}").getAsJsonObject();var state=LoadingBriefStore.decode(legacy);assertEquals(Set.of("threads","water"),state.seen());assertEquals("water",state.last());}
    @Test void loadingBriefManifestHasSixteenOwnedLinkedLessonsWithWideArt()throws Exception{var root=JsonParser.parseString(Files.readString(Path.of("src/main/resources/assets/better_content_threads/loading_briefs/catalogue.json"))).getAsJsonObject();assertEquals("bc.loading_briefs.v3",root.get("schema").getAsString());var briefs=root.getAsJsonArray("briefs");assertEquals(16,briefs.size());assertEquals(List.of("threads","hud","water","nutrition","variety","metabolism","temperature","movement","sleep","downing","life","seasons","weather","pollution","physics","campaigns"),java.util.stream.StreamSupport.stream(briefs.spliterator(),false).map(element->element.getAsJsonObject().get("id").getAsString()).toList());var threads=JsonParser.parseString(Files.readString(Path.of("src/main/resources/data/better_content_threads/threads/catalogue.json"))).getAsJsonObject().getAsJsonArray("threads");var concepts=new HashMap<String,String>();for(var element:threads){var row=element.getAsJsonObject();concepts.put(row.get("id").getAsString(),row.get("concept_id").getAsString());}for(var element:briefs){var brief=LoadingBrief.parse(element.getAsJsonObject());assertFalse(brief.owner().isBlank(),brief.id());if(!brief.relatedThread().isEmpty())assertEquals(brief.conceptId(),concepts.get(brief.relatedThread()),brief.id());var path=Path.of("src/main/resources/assets/better_content_threads",brief.art().getPath());var image=ImageIO.read(path.toFile());assertNotNull(image,brief.id());assertEquals(512,image.getWidth(),brief.id());assertEquals(256,image.getHeight(),brief.id());}String movement=briefs.get(7).getAsJsonObject().get("body").getAsString();assertTrue(movement.contains("directional double-tap dodging is disabled"));assertFalse(movement.contains("double taps also dodge"));}
    @Test void loadingBriefLayoutKeepsProgressLessonsAndControlsSeparate(){for(var size:List.of(new int[]{320,240},new int[]{427,240},new int[]{854,480},new int[]{1920,1080})){var layout=LoadingBriefLayout.calculate(size[0],size[1],true);assertTrue(layout.barX()>=0);assertTrue(layout.barX()+layout.barWidth()<=size[0]);assertTrue(layout.panelY()>layout.barY()+8);assertTrue(layout.panelX()>=0);assertTrue(layout.panelX()+layout.panelWidth()<=size[0]);assertTrue(layout.panelY()+layout.panelHeight()<layout.controlsY());assertTrue(layout.controlsY()+20<=size[1]);if(layout.showArt())assertEquals(layout.artWidth(),layout.artHeight()*2);}}
    @Test void joinBriefCarriesIntoArrivalOnlyAfterExplicitOptIn()throws Exception{String client=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadClient.java"));String screen=Files.readString(Path.of("src/main/java/com/bettercontent/threads/LoadingBriefScreen.java"));String generation=Files.readString(Path.of("src/main/java/com/bettercontent/threads/LearningLevelLoadingScreen.java"));assertTrue(client.contains("ClientPlayerNetworkEvent.LoggingIn"));assertTrue(client.contains("isInitialLoadScreen"));assertTrue(client.contains("if (currentBriefs.keepReading())"));assertTrue(client.contains("else {\n                dismissBrief();"));assertFalse(client.contains("PlayerChangedDimensionEvent"));assertTrue(generation.contains("toggleKeepReading"));assertTrue(screen.contains("GLFW.GLFW_KEY_ENTER"));assertTrue(screen.contains("GLFW.GLFW_KEY_SPACE"));assertTrue(screen.contains("GLFW.GLFW_KEY_ESCAPE"));assertTrue(screen.contains("closeBrief();"));assertFalse(screen.contains("shouldCloseOnEsc() { return false; }"));}
    @Test void lessonsRemainAvailableInsideThreadsWithoutLeakingUnknownCards()throws Exception{String deck=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadDeckScreen.java"));String library=Files.readString(Path.of("src/main/java/com/bettercontent/threads/LearningLibraryScreen.java"));assertTrue(deck.contains("new LearningLibraryScreen(cards)"));assertTrue(library.contains("LoadingBriefs.INSTANCE.all()"));assertTrue(library.contains("card != null && card.known() && !card.doorwayType().isEmpty()"));assertTrue(library.contains("ThreadDoorways.open(card)"));assertTrue(library.contains("LoadingBriefStore.save(state)"));}
    @Test void blockedEndRouteUsesTheNewCorrelatedContract()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java"));assertTrue(source.contains("Items.ENDER_EYE"));assertTrue(source.contains("\"end_route_blocked\",\"eye_or_portal\""));assertTrue(source.contains("activeCorrelation(player,\"the_end_is_not_a_door\")"));}
    @Test void emiViewAndSubsequentCraftUseOneServerOwnedEpisode()throws Exception{String client=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadClient.java"));String network=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadNetwork.java"));String events=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java"));assertTrue(client.contains("dev.emi.emi.screen.RecipeScreen"));assertTrue(client.contains("ThreadNetwork.request(\"recipe_viewed\""));assertTrue(network.contains("\"recipe_viewed\",\"emi\""));assertTrue(events.contains("PlayerEvent.ItemCraftedEvent"));assertTrue(events.contains("\"pack_recipe_crafted\",\"registered\",token"));}
    @Test void contextualEventsContainNoLoginDiscovery()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java"));String login=source.substring(source.indexOf("void login"),source.indexOf("void logout"));assertFalse(login.contains("ThreadSignals.emit"));}
    @Test void contextualEventsUseNativePickupAndIgnoreQuietCampaignState()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java"));assertTrue(source.contains("ItemPickupEvent"));assertTrue(source.contains("visit.acquired=true"));assertFalse(source.contains("inventoryTypes("));assertTrue(source.contains("current.equals(\"quiet\")"));}
    @Test void forestAnchorUsesNativeMatureAndEstablishedTreeEvidence()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/DynamicTreeThreads.java"));assertTrue(source.contains("instanceof BranchBlock"));assertTrue(source.contains("MATURE_RADIUS = 8"));assertTrue(source.contains("TransitionSaplingToTreeEvent"));assertTrue(source.contains("getFamily().getRegistryName()"));}
    @Test void createRoutesUseOnlyActionBackedNativeCriteria()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/NativeAdvancementThreads.java"));assertTrue(source.contains("create:hand_crank_000"));assertTrue(source.contains("create:mechanical_press"));assertTrue(source.contains("create:water_wheel"));assertTrue(source.contains("create:mechanical_pump_0"));assertTrue(source.contains("create:train"));assertTrue(source.contains("create:long_travel"));assertFalse(source.contains("inventory_changed"));}
    @Test void packActionRoutesUseActualOperatingStateAndCorrelatedHardware()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/PackActionThreads.java"));String ae2=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/Ae2Threads.java"));String power=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/PowerGridThreads.java"));assertTrue(ae2.contains("instanceof PatternEncodingTermMenu"));assertTrue(power.contains("getExternalNodes"));assertTrue(power.contains("Math.abs(node.getCurrent())"));assertTrue(source.contains("vessel_landfall"));assertTrue(source.contains("source_machine"));}
    @Test void vesselProbeDoesNotReflectAcrossClientOnlyValkyrienSkiesOverloads()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/PackActionThreads.java"));String compat=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/ValkyrienSkiesThreads.java"));assertFalse(source.contains("getMethod(\"getShipManaging\""));assertTrue(compat.contains("VSGameUtilsKt.getShipManaging(player)"));assertFalse(compat.contains("net.minecraft.client"));}
    @Test void relicRouteUsesPositiveNativeExperienceOnTheSamePhysicalStack()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/RelicsThreads.java"));assertTrue(source.contains("ExperienceAddEvent"));assertTrue(source.contains("event.getAmount() <= 0"));assertTrue(source.contains("same physical relic"));assertTrue(source.contains("active.equals(tag.getString(RELIC_TOKEN))"));}
    @Test void optionalMachineMixinsTargetNativeCompletionBoundaries()throws Exception{String ae2=Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/Ae2CraftingCpuMixin.java"));assertTrue(ae2.contains("method = \"done\""));String occult=Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/OccultismRitualBowlMixin.java"));assertTrue(occult.contains("method = \"startRitual\""));assertTrue(occult.contains("method = \"stopRitual\""));String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/ArsSourceEnergyMixin.java"));assertTrue(source.contains("method = \"addSource\""));}
    @Test void typedOptionalIntegrationsDeclareExactSupportedVersions()throws Exception{
        String metadata=Files.readString(Path.of("src/main/resources/META-INF/mods.toml"));
        var blocks=Arrays.asList(metadata.split(java.util.regex.Pattern.quote("[[dependencies.${mod_id}]]")));
        var expected=Map.ofEntries(
            Map.entry("arcane_chunk_loaders","[0.1.0]"),Map.entry("better_content_economy","[1.0.1]"),
            Map.entry("better_content_fixes","[0.1.7]"),Map.entry("dimension_drink","[1.0.0]"),
            Map.entry("downed_player_revival","[1.0.0]"),Map.entry("heat_sync","[0.1.0]"),
            Map.entry("pillager_campaigns","[0.5.4]"),Map.entry("player_traces","[0.1.0]"),
            Map.entry("rpg_stats","[1.0.1]"),Map.entry("realistic_ores","[0.2.0]"),
            Map.entry("settlement_roads","[0.1.0]"),Map.entry("systemic_salience","[0.1.1]"),
            Map.entry("water_survival","[1.1.0]"),Map.entry("world_lifecycle_manager","[0.1.0]"),
            Map.entry("ae2","[15.4.10]"),Map.entry("arseng","[1.2.0]"),
            Map.entry("creatingspace","[1.20.1_1.7.13]"),Map.entry("powergrid","[0.5.4]"),
            Map.entry("dynamictrees","[1.20.1-1.4.10]"),Map.entry("sereneseasons","[9.1.0.2]"),
            Map.entry("weather2","[1.20.1-2.8.3]"),Map.entry("pneumaticcraft","[6.0.22+mc1.20.1]"),
            Map.entry("ars_nouveau","[4.12.7]"),Map.entry("bloodmagic","[3.3.7-49]"),
            Map.entry("goety","[2.5.53.1]"),Map.entry("tconstruct","[3.11.2.166]"),
            Map.entry("relics","[0.8.0.13]"),Map.entry("valkyrienskies","[2.4.11]"),
            Map.entry("occultism","[1.157.0]"),Map.entry("emi","[1.1.24]"),
            Map.entry("ponder","[1.0.92]"),Map.entry("create","[6.0.8]"));
        expected.forEach((id,range)->assertEquals(1,blocks.stream().filter(block->block.contains("modId=\""+id+"\"")&&block.contains("mandatory=false")&&block.contains("versionRange=\""+range+"\"")).count(),id));
    }
    @Test void pressureRouteRequiresAWorkingPressurizedCompressor()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/PneumaticThreads.java"));assertTrue(source.contains("compressor.isActive()"));assertTrue(source.contains("compressor.getPressure() <= 0.1f"));assertTrue(Files.readString(Path.of("src/main/java/com/bettercontent/threads/NativeAdvancementThreads.java")).contains("pneumaticcraft:pressure_chamber"));}
    @Test void atmosphereRouteUsesTheInstalledReadyRocketAndExactOrbit()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/CreatingSpaceThreads.java"));assertTrue(source.contains("rocket.destination == null || rocket.totalThrust <= 0.0f || rocket.deltaV() <= 0.0f"));assertTrue(Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java")).contains("creatingspace:earth_orbit"));String catalogue=Files.readString(Path.of("src/main/resources/data/better_content_threads/threads/catalogue.json"));assertFalse(catalogue.contains("compat.ad-astra"));}
    @Test void authoredArsSpellsCompleteOnlyOnMatchingNativeEffect()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/ArsNouveauThreads.java"));assertTrue(source.contains("EffectResolveEvent.Post"));assertTrue(source.contains("signature.equals(state.getString"));assertTrue(source.contains("token.equals(active)"));String mixin=Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/ArsUpdateCasterMixin.java"));assertTrue(mixin.contains("PacketUpdateCaster"));assertTrue(mixin.contains("spellRecipe.clone()"));}
    @Test void bloodRouteUsesActualAltarFillAndPlayerSoulSyphon()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/BloodMagicThreads.java"));assertTrue(source.contains("event.shouldFillAltar"));assertTrue(source.contains("event.lpAdded <= 0"));assertTrue(source.contains("SoulNetworkEvent.Syphon.User"));assertTrue(source.contains("activeCorrelation(player, \"blood_infrastructure\")"));}
    @Test void goetyRouteCorrelatesNativeSoulGainAndSpellWork()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/GoetyThreads.java"));assertTrue(source.contains("ChangeSoulEnergyEvent.Gain"));assertTrue(source.contains("event.getSoulChange() <= 0"));assertTrue(source.contains("CastMagicEvent"));assertTrue(source.contains("activeCorrelation(player, \"dead_leave_work\")"));}
    @Test void enchantRouteMarksActualAnvilOutputAndWaitsForItsEffect()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java"));assertTrue(source.contains("AnvilRepairEvent"));assertTrue(source.contains("entry.getValue()>before.getOrDefault"));assertTrue(source.contains("Enchantments.BLOCK_EFFICIENCY"));assertTrue(source.contains("EnchantmentHelper.getDamageBonus"));assertTrue(source.contains("token.equals(ThreadSignals.activeCorrelation(player,\"rules_adhere_matter\"))"));}
    @Test void tinkerRepairCorrelatesActualWornUseAndReducedDamageOutput()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/TConstructThreads.java"));assertTrue(source.contains("TinkerToolEvent.ToolHarvestEvent"));assertTrue(source.contains("damage * 2 < total"));assertTrue(source.contains("ToolStack.from(output).getDamage() >= before"));assertTrue(source.contains("activeCorrelation(player, \"hands_learn_repair\")"));}
    @Test void tinkerAlloyRequiresNativeRecipeAndSameSmelteryOutput()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/TConstructThreads.java"));assertTrue(source.contains("getAlloyingModule().canAlloy()"));assertTrue(source.contains("position != state.getLong(\"position\")"));assertTrue(source.contains("activeCorrelation(player, \"materials_temperaments\")"));assertTrue(Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/TinkerAlloyMixin.java")).contains("doAlloy"));}
    @Test void downedIntegrationUsesThePublishedLifecycleEvent()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/bettercontent/DownedRevivalThreads.java"));assertTrue(source.contains("PlayerDownedEvent"));assertTrue(source.contains("\"downed\", \"player\""));}
    @Test void betterContentDomainEventsPreserveExistingCorrelations()throws Exception{String dimension=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/bettercontent/DimensionDrinkThreads.java"));String stats=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/bettercontent/RpgStatsThreads.java"));assertTrue(dimension.contains("event.getRunId().toString()"));assertTrue(dimension.contains("font_route_completed"));assertTrue(dimension.contains("activeCorrelation(event.getPlayer(), \"the_end_is_not_a_door\")"));assertTrue(stats.contains("event.getEpisodeId()"));assertTrue(stats.contains("case AVAILABLE"));assertTrue(stats.contains("case SPENT"));}
    @Test void everyFacsimileOverrideResolvesToAPackagedCardTexture()throws Exception{
        Path assets=Path.of("src/main/resources/assets");
        var dispatch=JsonParser.parseString(Files.readString(assets.resolve("better_content_threads/models/item/thread_facsimile.json"))).getAsJsonObject();
        var overrides=dispatch.getAsJsonArray("overrides");
        var fallback=dispatch.getAsJsonObject("textures");
        assertEquals("minecraft:item/paper",fallback.get("layer0").getAsString());
        assertEquals("minecraft:item/paper",fallback.get("particle").getAsString());
        assertNotNull(getClass().getClassLoader().getResource("assets/better_content_threads/models/item/thread_facsimile.json"));
        Set<String> newCards=Set.of("coins_do_not_climb","food_carries_weather","hunger_is_not_nutrition","recipes_obey_this_world","sleep_is_not_an_anchor","the_body_learns_new_motions","the_end_is_not_a_door");
        assertEquals(ThreadArt.IDS.size(),overrides.size());
        for(int index=0;index<ThreadArt.IDS.size();index++){
            String id=ThreadArt.IDS.get(index);
            var override=overrides.get(index).getAsJsonObject();
            assertEquals(index+1,override.getAsJsonObject("predicate").get("better_content_threads:thread_index").getAsInt(),id);
            assertEquals("better_content_threads:item/thread_cards/"+id,override.get("model").getAsString(),id);

            Path modelPath=assets.resolve("better_content_threads/models/item/thread_cards/"+id+".json");
            assertTrue(Files.isRegularFile(modelPath),id+" model");
            assertNotNull(getClass().getClassLoader().getResource("assets/better_content_threads/models/item/thread_cards/"+id+".json"),id+" packaged model");
            var model=JsonParser.parseString(Files.readString(modelPath)).getAsJsonObject();
            assertEquals("minecraft:item/generated",model.get("parent").getAsString(),id);
            var textures=model.getAsJsonObject("textures");
            String texture=textures.get("layer0").getAsString();
            assertEquals("better_content_threads:item/thread_cards/"+id,texture,id+" atlas sprite");
            assertEquals(texture,textures.has("particle")?textures.get("particle").getAsString():texture,id+" particle");
            String[] location=texture.split(":",2);
            assertTrue(location[1].startsWith("item/")||location[1].startsWith("block/"),id+" must be admitted by the item/block atlas");
            Path texturePath=assets.resolve(location[0]).resolve("textures").resolve(location[1]+".png");
            assertTrue(Files.isRegularFile(texturePath),id+" texture: "+texturePath);
            assertNotNull(ImageIO.read(texturePath.toFile()),id+" readable texture");
            String packagedTexture="assets/"+location[0]+"/textures/"+location[1]+".png";
            assertNotNull(getClass().getClassLoader().getResource(packagedTexture),id+" packaged texture");
            if(newCards.contains(id)){
                Path canonical=assets.resolve("better_content_threads/textures/gui/threads/"+id+".png");
                assertArrayEquals(Files.readAllBytes(canonical),Files.readAllBytes(texturePath),id+" canonical art copy");
            }
        }
    }
}
