package com.bettercontent.threads;

import com.google.gson.JsonParser;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraftforge.client.event.RenderGuiEvent;
import net.minecraftforge.client.event.RenderGuiOverlayEvent;
import org.junit.jupiter.api.Test;
import javax.imageio.ImageIO;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

final class ThreadContractsTest {
    @Test void catalogueContainsFourOrderedSuitsOfThirteen(){assertEquals(52,ThreadArt.IDS.size());assertEquals(52,new HashSet<>(ThreadArt.IDS).size());for(var suit:ThreadSuit.values())assertEquals(java.util.stream.IntStream.rangeClosed(1,13).boxed().toList(),ThreadArt.ENTRIES.stream().filter(e->e.suit()==suit).map(ThreadArt.Entry::order).toList());assertEquals(7,ThreadArt.ENTRIES.stream().filter(ThreadArt.Entry::future).count());}
    @Test void exactAssignmentsCoverEveryIdentity(){assertEquals(new HashSet<>(ThreadArt.IDS),ThreadArt.EXPECTED_ASPECTS.keySet());var retained=Map.ofEntries(Map.entry("stone_makes_promises",ThreadAspect.WORK),Map.entry("world_remembers",ThreadAspect.CONTROL),Map.entry("pollen_keeps_a_pantry",ThreadAspect.ROBUSTNESS),Map.entry("logistics_has_ruins",ThreadAspect.ENDURANCE),Map.entry("feast_before_journey",ThreadAspect.ENDURANCE),Map.entry("materials_temperaments",ThreadAspect.ROBUSTNESS),Map.entry("pressure_changes_matter",ThreadAspect.IMPACT),Map.entry("rails_turn_distance",ThreadAspect.TEMPO),Map.entry("leave_atmosphere",ThreadAspect.ENDURANCE),Map.entry("blood_infrastructure",ThreadAspect.RENEWAL),Map.entry("army_walks_toward_you",ThreadAspect.IMPACT));retained.forEach((id,aspect)->assertEquals(aspect,ThreadArt.EXPECTED_ASPECTS.get(id),id));assertEquals(ThreadAspect.RENEWAL,ThreadArt.EXPECTED_ASPECTS.get("defeat_not_erasure"));}
    @Test void liveDefinitionsRequireRoutesInvitationAndDoorway(){var json=JsonParser.parseString("{\"id\":\"test\",\"title\":\"Test\",\"suit\":\"world\",\"order\":1,\"aspect\":\"control\",\"art\":\"better_content_threads:textures/gui/threads/test.png\",\"prose\":\"Prose\",\"invitation\":\"Invitation\",\"action\":\"Do it.\",\"reveal_routes\":[{\"id\":\"r\",\"label\":\"Reveal\",\"type\":\"event\",\"value\":\"a\",\"producer\":\"test-producer\",\"correlation\":\"episode\"}],\"completion_routes\":[{\"id\":\"c\",\"label\":\"Complete\",\"type\":\"event\",\"value\":\"b\",\"producer\":\"test-producer\",\"correlation\":\"episode\"}],\"doorway\":{\"type\":\"emi\",\"target\":\"minecraft:stone\"}}").getAsJsonObject();var definition=ThreadDefinition.parse(json);assertFalse(definition.future());assertEquals(1,definition.revealRoutes().size());json.remove("completion_routes");assertThrows(IllegalArgumentException.class,()->ThreadDefinition.parse(json));}
    @Test void everyLiveRouteHasExactProducerAndCorrelationCoverage()throws Exception{var catalogue=JsonParser.parseString(Files.readString(Path.of("src/main/resources/data/better_content_threads/threads/catalogue.json"))).getAsJsonArray();int live=0,routes=0;var keys=new HashSet<String>();for(var element:catalogue){var json=element.getAsJsonObject();if(json.has("future")&&json.get("future").getAsBoolean())continue;live++;var definition=ThreadDefinition.parse(json);for(var route:java.util.stream.Stream.concat(definition.revealRoutes().stream(),definition.completionRoutes().stream()).toList()){routes++;assertFalse(route.producer().isBlank());assertEquals("episode",route.correlation());assertTrue(keys.add(definition.id()+":"+route.id()));}}assertEquals(45,live);assertEquals(94,routes);assertEquals(94,keys.size());}
    @Test void futureDefinitionsForbidTriggerOrLoreLeaks(){var json=JsonParser.parseString("{\"id\":\"future\",\"title\":\"Future\",\"suit\":\"fragility\",\"order\":7,\"aspect\":\"impact\",\"art\":\"better_content_threads:textures/gui/threads/future.png\",\"future\":true}").getAsJsonObject();assertTrue(ThreadDefinition.parse(json).future());json.addProperty("prose","Leak");assertThrows(IllegalArgumentException.class,()->ThreadDefinition.parse(json));}
    @Test void aspectsAndSuitsUseExactIdsAndColors(){assertEquals(0xE4717D,ThreadAspect.IMPACT.color());assertEquals(0x8A6CB2,ThreadAspect.CONTROL.color());assertEquals(0x66704C,ThreadSuit.WORLD.color());assertEquals(0x805356,ThreadSuit.FRAGILITY.color());assertThrows(IllegalArgumentException.class,()->ThreadAspect.parse("Control"));assertThrows(IllegalArgumentException.class,()->ThreadSuit.parse("World"));}
    @Test void noticePayloadContainsNoGameAssetOrProse(){assertArrayEquals(new String[]{"kind","id","title","suit","aspect"},Arrays.stream(ThreadNetwork.Notice.class.getRecordComponents()).map(java.lang.reflect.RecordComponent::getName).toArray(String[]::new));assertDoesNotThrow(()->new ThreadNetwork.Notice(ThreadNetwork.NoticeKind.REVEAL,"world_remembers","The World Remembers","world","endurance"));assertThrows(IllegalArgumentException.class,()->new ThreadNetwork.Notice(ThreadNetwork.NoticeKind.REVEAL,"world_remembers","The World Remembers","world","Control"));}
    @Test void automaticTeaseUsesSmallCodeGlyphLockup(){assertEquals(8,ThreadClient.NOTICE_GLYPH_SIZE);assertTrue(ThreadClient.NOTICE_TEXT_SCALE<1);assertEquals(2,ThreadClient.NOTICE_TEXT_OFFSET_Y-(ThreadClient.NOTICE_GLYPH_OFFSET_Y+ThreadClient.NOTICE_GLYPH_SIZE));assertTrue(ThreadClient.NOTICE_HINT_SCALE<ThreadClient.NOTICE_TEXT_SCALE);assertTrue(ThreadClient.NOTICE_HINT_OFFSET_Y>ThreadClient.NOTICE_TEXT_OFFSET_Y);}
    @Test void automaticTeaseUsesExactLocalizedCopy()throws Exception{var lang=JsonParser.parseString(Files.readString(Path.of("src/main/resources/assets/better_content_threads/lang/en_us.json"))).getAsJsonObject();assertEquals("You've revealed the card: %s",lang.get("message.better_content_threads.thread_revealed").getAsString());assertEquals("%1$s+%2$s · Open Threads",lang.get("message.better_content_threads.thread_reader_hint").getAsString());}
    @Test void automaticTeaseRendersOnceAfterTheWholeGui()throws Exception{assertNotNull(ThreadClient.class.getDeclaredMethod("render",RenderGuiEvent.Post.class));assertThrows(NoSuchMethodException.class,()->ThreadClient.class.getDeclaredMethod("render",RenderGuiOverlayEvent.Post.class));}
    @Test void cardArtScalesTheEntireNativeTexture()throws Exception{assertEquals(256,ThreadClient.ART_TEXTURE_WIDTH);assertEquals(384,ThreadClient.ART_TEXTURE_HEIGHT);String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadClient.java"));assertTrue(source.contains("graphics.blit(id, x, y, width, height, 0.0f, 0.0f,"));}
    @Test void detailLayoutCentersTheSplitCompositionAtWideAndCompactSizes(){for(var size:List.of(new int[]{854,480},new int[]{320,240})){var layout=ThreadDeckScreen.detailLayout(size[0],size[1]);int contentWidth=layout.cardWidth()+18+layout.panelWidth();assertTrue(Math.abs((layout.cardX()*2+contentWidth)-size[0])<=1);assertEquals(layout.cardX()+layout.cardWidth()+18,layout.detailsX());assertTrue(layout.cardHeight()<=300);assertTrue(Math.abs(layout.cardWidth()*3-layout.cardHeight()*2)<=2);}}
    @Test void readerLocalizesExplicitRevealCues()throws Exception{var lang=JsonParser.parseString(Files.readString(Path.of("src/main/resources/assets/better_content_threads/lang/en_us.json"))).getAsJsonObject();assertEquals("REVEAL",lang.get("screen.better_content_threads.reveal_badge").getAsString());assertEquals("%1$s of 13 remembered · %2$s to reveal",lang.get("screen.better_content_threads.catalogue_status_unread").getAsString());String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadDeckScreen.java"));assertTrue(source.contains("unreadCount(candidate)"));assertTrue(source.contains("selected = firstUnreadIndex(suitCards())"));assertTrue(source.contains("scrollRow = selected / CATALOGUE_COLUMNS"));}
    @Test void noticesQueueByKindAndPauseWithoutAdvancing(){var queue=new ThreadNoticeQueue<String>(value->value);queue.addAll(List.of("reveal:first","complete:first","reveal:first"));assertEquals(2,queue.size());var first=queue.advance(0,false);assertEquals("reveal:first",first.notice());assertTrue(first.started());assertEquals(0,queue.advance(900,true).elapsedMs());assertNull(queue.advance(3_200,false));assertEquals("complete:first",queue.advance(0,false).notice());}
    @Test void readStateChangesOnlyAfterEightHundredMillisecondDevelopment(){var reveal=new ThreadRevealState();reveal.select(true);assertEquals(ThreadRevealState.Activation.STARTED,reveal.activate());assertFalse(reveal.advance(799));assertTrue(reveal.advance(1));assertEquals(ThreadRevealState.Phase.COMPLETE,reveal.phase());}
    @Test void developmentSkipIsConsumedBeforeControls(){var reveal=new ThreadRevealState();reveal.select(true);assertEquals(ThreadRevealState.Activation.STARTED,reveal.activate());assertEquals(ThreadRevealState.Activation.COMPLETED,reveal.activate());assertEquals(ThreadRevealState.Activation.IGNORED,reveal.activate());}
    @Test void runtimeArtUsesOnlyUntouchedImagesAndThumbnails()throws Exception{Path root=Path.of("src/main/resources/assets/better_content_threads/textures/gui/threads");try(var files=Files.list(root)){var names=files.filter(Files::isRegularFile).map(path->path.getFileName().toString()).toList();assertEquals(104,names.size());assertFalse(names.stream().anyMatch(name->name.endsWith("_archive.png")||name.endsWith("_pigment.png")||name.endsWith("_aspect.png")));}for(String id:ThreadArt.IDS){for(String suffix:List.of(".png","_thumb.png")){var image=ImageIO.read(root.resolve(id+suffix).toFile());assertNotNull(image,id+suffix);assertEquals(256,image.getWidth(),id+suffix);assertEquals(384,image.getHeight(),id+suffix);}}}
    @Test void oldCollectedStateMigratesAsKnownWithoutCompletion(){var root=new CompoundTag();var collected=new ListTag();collected.add(StringTag.valueOf("world_remembers"));root.put("collected",collected);var state=ThreadPlayerState.fromTag(root);assertTrue(state.known.contains("world_remembers"));assertTrue(state.completed.isEmpty());assertEquals(0,state.completionCounts.size());}
    @Test void emptyLineageImportsWorldLocalStateButEstablishedLineageWins(){var local=new CompoundTag();local.putString("source","world");var lineage=new CompoundTag();assertSame(local,ThreadPlayerState.preferLineageState(lineage,local));lineage.putString("source","lineage");assertSame(lineage,ThreadPlayerState.preferLineageState(lineage,local));}
    @Test void completionHistoryIsMonotonicAndRouteAware(){var root=new CompoundTag();var known=new ListTag();known.add(StringTag.valueOf("world_remembers"));root.put("known",known);var active=new ListTag();active.add(StringTag.valueOf("world_remembers"));root.put("active",active);var state=ThreadPlayerState.fromTag(root);assertTrue(state.complete("world_remembers","Returned trace",3));assertFalse(state.complete("world_remembers","Returned trace",3));assertEquals(1,state.completionCounts.get("world_remembers"));assertEquals("Returned trace ×1",state.routeSummary("world_remembers"));}
    @Test void correlationsPersistRebindAndClearOnlyAfterCompletion(){var state=new ThreadPlayerState();assertTrue(state.reveal("world_remembers","episode-a"));assertEquals("episode-a",state.correlations.get("world_remembers"));var restored=ThreadPlayerState.fromTag(state.toTag());assertEquals("episode-a",restored.correlations.get("world_remembers"));assertTrue(restored.bindCorrelation("world_remembers","episode-b"));assertEquals("episode-b",restored.correlations.get("world_remembers"));assertTrue(restored.complete("world_remembers","Returned trace",1));assertFalse(restored.correlations.containsKey("world_remembers"));}
    @Test void knownCardReactivatesInSuccessorWithoutBecomingUnreadAgain(){var state=new ThreadPlayerState();assertTrue(state.reveal("world_remembers"));assertTrue(state.markRead("world_remembers"));state.enterGeneration(1);assertTrue(state.reveal("world_remembers"));assertTrue(state.active.contains("world_remembers"));assertFalse(state.unread.contains("world_remembers"));assertFalse(state.reveal("world_remembers"));}
    @Test void contextualEventsContainNoLoginDiscovery()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java"));String login=source.substring(source.indexOf("void login"),source.indexOf("void logout"));assertFalse(login.contains("ThreadSignals.emit"));}
    @Test void contextualEventsUseNativePickupAndIgnoreQuietCampaignState()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java"));assertTrue(source.contains("ItemPickupEvent"));assertTrue(source.contains("visit.acquired=true"));assertFalse(source.contains("inventoryTypes("));assertTrue(source.contains("current.equals(\"quiet\")"));}
    @Test void forestAnchorUsesNativeMatureAndEstablishedTreeEvidence()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/DynamicTreeThreads.java"));assertTrue(source.contains("instanceof BranchBlock"));assertTrue(source.contains("MATURE_RADIUS = 8"));assertTrue(source.contains("TransitionSaplingToTreeEvent"));assertTrue(source.contains("getFamily().getRegistryName()"));}
    @Test void createRoutesUseOnlyActionBackedNativeCriteria()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/NativeAdvancementThreads.java"));assertTrue(source.contains("create:hand_crank_000"));assertTrue(source.contains("create:mechanical_press"));assertTrue(source.contains("create:water_wheel"));assertTrue(source.contains("create:mechanical_pump_0"));assertTrue(source.contains("create:train"));assertTrue(source.contains("create:long_travel"));assertFalse(source.contains("inventory_changed"));}
    @Test void packActionRoutesUseActualOperatingStateAndCorrelatedHardware()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/PackActionThreads.java"));assertTrue(source.contains("PatternEncoding"));assertTrue(source.contains("getExternalNodes"));assertTrue(source.contains("Math.abs(current)"));assertTrue(source.contains("vessel_landfall"));assertTrue(source.contains("source_machine"));}
    @Test void vesselProbeDoesNotReflectAcrossClientOnlyValkyrienSkiesOverloads()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/PackActionThreads.java"));String compat=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/ValkyrienSkiesThreads.java"));assertFalse(source.contains("getMethod(\"getShipManaging\""));assertTrue(compat.contains("VSGameUtilsKt.getShipManaging(player)"));assertFalse(compat.contains("net.minecraft.client"));}
    @Test void relicRouteUsesPositiveNativeExperienceOnTheSamePhysicalStack()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/RelicsThreads.java"));assertTrue(source.contains("ExperienceAddEvent"));assertTrue(source.contains("event.getAmount() <= 0"));assertTrue(source.contains("same physical relic"));assertTrue(source.contains("active.equals(tag.getString(RELIC_TOKEN))"));}
    @Test void optionalMachineMixinsTargetNativeCompletionBoundaries()throws Exception{String ae2=Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/Ae2CraftingCpuMixin.java"));assertTrue(ae2.contains("method = \"done\""));String occult=Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/OccultismRitualBowlMixin.java"));assertTrue(occult.contains("method = \"startRitual\""));assertTrue(occult.contains("method = \"stopRitual\""));String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/ArsSourceEnergyMixin.java"));assertTrue(source.contains("method = \"addSource\""));}
    @Test void pressureRouteRequiresAWorkingPressurizedCompressor()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/PneumaticThreads.java"));assertTrue(source.contains("compressor.isActive()"));assertTrue(source.contains("compressor.getPressure() <= 0.1f"));assertTrue(Files.readString(Path.of("src/main/java/com/bettercontent/threads/NativeAdvancementThreads.java")).contains("pneumaticcraft:pressure_chamber"));}
    @Test void atmosphereRouteUsesTheInstalledReadyRocketAndExactOrbit()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/CreatingSpaceThreads.java"));assertTrue(source.contains("destination == null || thrust <= 0.0f || deltaV <= 0.0f"));assertTrue(Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java")).contains("creatingspace:earth_orbit"));String catalogue=Files.readString(Path.of("src/main/resources/data/better_content_threads/threads/catalogue.json"));assertFalse(catalogue.contains("compat.ad-astra"));}
    @Test void authoredArsSpellsCompleteOnlyOnMatchingNativeEffect()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/ArsNouveauThreads.java"));assertTrue(source.contains("EffectResolveEvent.Post"));assertTrue(source.contains("signature.equals(state.getString"));assertTrue(source.contains("token.equals(active)"));String mixin=Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/ArsUpdateCasterMixin.java"));assertTrue(mixin.contains("PacketUpdateCaster"));assertTrue(mixin.contains("spellRecipe.clone()"));}
    @Test void bloodRouteUsesActualAltarFillAndPlayerSoulSyphon()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/BloodMagicThreads.java"));assertTrue(source.contains("event.shouldFillAltar"));assertTrue(source.contains("event.lpAdded <= 0"));assertTrue(source.contains("SoulNetworkEvent.Syphon.User"));assertTrue(source.contains("activeCorrelation(player, \"blood_infrastructure\")"));}
    @Test void goetyRouteCorrelatesNativeSoulGainAndSpellWork()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/GoetyThreads.java"));assertTrue(source.contains("ChangeSoulEnergyEvent.Gain"));assertTrue(source.contains("event.getSoulChange() <= 0"));assertTrue(source.contains("CastMagicEvent"));assertTrue(source.contains("activeCorrelation(player, \"dead_leave_work\")"));}
    @Test void enchantRouteMarksActualAnvilOutputAndWaitsForItsEffect()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java"));assertTrue(source.contains("AnvilRepairEvent"));assertTrue(source.contains("entry.getValue()>before.getOrDefault"));assertTrue(source.contains("Enchantments.BLOCK_EFFICIENCY"));assertTrue(source.contains("EnchantmentHelper.getDamageBonus"));assertTrue(source.contains("token.equals(ThreadSignals.activeCorrelation(player,\"rules_adhere_matter\"))"));}
    @Test void tinkerRepairCorrelatesActualWornUseAndReducedDamageOutput()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/TConstructThreads.java"));assertTrue(source.contains("TinkerToolEvent.ToolHarvestEvent"));assertTrue(source.contains("damage * 2 < total"));assertTrue(source.contains("ToolStack.from(output).getDamage() >= before"));assertTrue(source.contains("activeCorrelation(player, \"hands_learn_repair\")"));}
    @Test void tinkerAlloyRequiresNativeRecipeAndSameSmelteryOutput()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/compat/TConstructThreads.java"));assertTrue(source.contains("getAlloyingModule().canAlloy()"));assertTrue(source.contains("position != state.getLong(\"position\")"));assertTrue(source.contains("activeCorrelation(player, \"materials_temperaments\")"));assertTrue(Files.readString(Path.of("src/main/java/com/bettercontent/threads/mixin/TinkerAlloyMixin.java")).contains("doAlloy"));}
    @Test void downedIntegrationUsesThePublishedPlayerSignature()throws Exception{String source=Files.readString(Path.of("src/main/java/com/bettercontent/threads/ThreadEvents.java"));assertTrue(source.contains("getMethod(\"isDowned\",net.minecraft.world.entity.player.Player.class)"));}
    @Test void everyFacsimileModelExists(){for(String id:ThreadArt.IDS)assertTrue(Files.isRegularFile(Path.of("src/main/resources/assets/better_content_threads/models/item/thread_cards",id+".json")),id);}
}
